"""The engine's complete board-item inventory, against a real build.

The DRC identity proof needs to know whether a violation's UUID names exactly
one physical item - and roughly half the findings name something the copper
accessors never return (a zone, a courtyard graphic, a footprint's own UUID).
These tests exercise the native accessor that closes that gap: it must cover
every container, name an item's parent, report a reused UUID as ambiguous, and
survive a save/reopen unchanged.

Everything here is a synthetic board generated by the repository's own fixture
helper; no private board is read or referenced.
"""

from __future__ import annotations

import re
from pathlib import Path

from pcb_world.agent.drc_gate import capture_inventory, resolve_item_identity
from tests.agent import synthetic_boards as sb

#: An arbitrary, deterministic UUID for a graphic injected into a footprint.
GRAPHIC_UUID = "11111111-2222-3333-4444-555555555555"

_FOOTPRINT_UUID = re.compile(r'\n    \(uuid "([0-9a-fA-F-]{36})"\)')

_GRAPHIC_SNIPPET = f"""    (fp_line
      (start 1 1)
      (end 2 2)
      (stroke (width 0.12) (type solid))
      (layer "F.SilkS")
      (uuid "{GRAPHIC_UUID}")
    )
"""


def _inject_footprint_graphic(text: str) -> str:
    """Add one ``fp_line`` graphic inside the first footprint.

    The generator has no footprint-graphic knob, and a graphic inside a
    footprint is exactly the kind of item the copper accessors miss.
    """
    match = _FOOTPRINT_UUID.search(text)
    assert match, "the synthetic board has no footprint to extend"
    insert_at = text.index("\n", match.start() + 1) + 1
    return text[:insert_at] + _GRAPHIC_SNIPPET + text[insert_at:]


def _reuse_first_footprint_uuid(text: str) -> str:
    """Give the second footprint the first footprint's UUID."""
    matches = list(_FOOTPRINT_UUID.finditer(text))
    assert len(matches) >= 2, "need two footprints to reuse a UUID"
    first = matches[0].group(1)
    second = matches[1]
    return (text[:second.start(1)] + first + text[second.end(1):])


def _rows(engine) -> set[tuple]:
    return {
        (row.uuid, row.kind, row.source, row.parent_kind, row.parent_ref,
         int(row.layer), int(row.net_code), row.physical_id)
        for row in engine.get_board_items()
    }


def test_native_inventory_covers_zones_graphics_and_footprint_children(
    native_engine_checked, board_dir
):
    """Zones, footprint graphics, fields and footprints are all named."""
    from pcb_world.engine import KiCadEngine

    board = sb.write_board(
        board_dir / "items.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PB1", 40.0, 10.0, 2)],
        segments=[sb.Segment(10.0, 10.0, 20.0, 10.0, 1)],
        zones=[sb.Zone(1, 5.0, 5.0, 25.0, 18.0)],
        nets=(1, 2), width=40.0, height=24.0,
    )
    text = Path(board).read_text(encoding="utf-8")
    Path(board).write_text(_inject_footprint_graphic(text), encoding="utf-8")

    engine = KiCadEngine(board)
    try:
        inventory = capture_inventory(engine)
        assert inventory.complete, inventory.problems
        assert not inventory.problems

        kinds = dict(inventory.kinds)
        assert kinds.get("zone") == 1
        assert kinds.get("pad") == 2
        assert kinds.get("footprint") == 2
        assert kinds.get("field", 0) >= 2          # reference + value fields
        assert kinds.get("shape", 0) >= 2          # board outline + fp_line
        assert not inventory.unknown_kinds, inventory.unknown_kinds

        # The board's own outline and every footprint child are identified.
        sources = {row.source for group in inventory.items.values()
                   for row in group}
        assert {"board.tracks", "board.pads", "board.zones", "board.drawings",
                "board.footprints", "footprint.graphics",
                "footprint.fields"} <= sources

        # A non-copper item is an identity once the complete inventory covers it.
        identity, why = resolve_item_identity(GRAPHIC_UUID, inventory)
        assert identity == GRAPHIC_UUID and why == "unique item"

        row = next(item for group in inventory.items.values() for item in group
                   if item.uuid == GRAPHIC_UUID)
        assert row.kind == "shape"
        assert row.parent_kind == "footprint"
        assert row.parent_ref == "PA1"
        assert inventory.nil_uuids == 0
    finally:
        engine.close()


def test_native_inventory_marks_a_reused_footprint_uuid_unverified(
    native_engine_checked, board_dir
):
    """A UUID two footprints carry proves neither: it stays unresolved."""
    from pcb_world.engine import KiCadEngine

    board = sb.write_board(
        board_dir / "duplicate_footprint.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PB1", 40.0, 10.0, 2)],
        nets=(1, 2), width=40.0, height=24.0,
    )
    text = Path(board).read_text(encoding="utf-8")
    matches = list(_FOOTPRINT_UUID.finditer(text))
    shared = matches[0].group(1)
    Path(board).write_text(_reuse_first_footprint_uuid(text), encoding="utf-8")

    engine = KiCadEngine(board)
    try:
        inventory = capture_inventory(engine)
        assert inventory.complete, inventory.problems
        assert inventory.duplicated_uuids >= 1
        assert inventory.duplicated_items >= 2
        assert len(inventory.candidates(shared)) == 2

        identity, why = resolve_item_identity(shared, inventory)
        assert identity is None
        assert "duplicate identifier" in why

        # An item that is not duplicated is still proven; the ambiguity is local.
        unique = next(uuid for uuid, group in inventory.items.items()
                      if len(group) == 1 and group[0].kind == "pad")
        assert resolve_item_identity(unique, inventory)[1] == "unique item"
    finally:
        engine.close()


def test_native_inventory_is_stable_across_save_and_reopen(
    native_engine_checked, board_dir
):
    """Every row - including the physical identity - survives a round trip."""
    from pcb_world.engine import KiCadEngine

    board = sb.write_board(
        board_dir / "roundtrip.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PB1", 40.0, 10.0, 2)],
        vias=[sb.Via(20.0, 12.0, 1)],
        zones=[sb.Zone(1, 5.0, 5.0, 25.0, 18.0)],
        nets=(1, 2), width=40.0, height=24.0,
    )
    text = Path(board).read_text(encoding="utf-8")
    Path(board).write_text(_inject_footprint_graphic(text), encoding="utf-8")

    saved = str(board_dir / "roundtrip_saved.kicad_pcb")
    engine = KiCadEngine(board)
    try:
        before = capture_inventory(engine)
        rows_before = _rows(engine)
        engine.save(saved)
    finally:
        engine.close()

    reopened = KiCadEngine(saved)
    try:
        after = capture_inventory(reopened)
        rows_after = _rows(reopened)
    finally:
        reopened.close()

    assert before.complete and after.complete
    assert before.item_count == after.item_count
    assert before.distinct_uuids == after.distinct_uuids
    assert rows_before == rows_after
    assert rows_after, "the inventory must not be empty"


def test_native_inventory_reports_a_partial_accessor_as_incomplete(
    native_engine_checked, board_dir
):
    """The fail-closed path: no complete accessor means no identity at all."""
    from pcb_world.engine import KiCadEngine

    board = sb.write_board(
        board_dir / "no_inventory.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PB1", 40.0, 10.0, 1)],
        nets=(1,), width=40.0, height=24.0,
    )
    engine = KiCadEngine(board)

    class WithoutInventory:
        """The engine as it looked before the complete accessor existed."""

        def __init__(self, real):
            self._real = real
            self.get_tracks = real.get_tracks
            self.get_vias = real.get_vias
            self.get_pads = real.get_pads

    try:
        inventory = capture_inventory(WithoutInventory(engine))
        assert inventory.complete is False
        assert "get_board_items()" in inventory.problems[0]
        assert resolve_item_identity("anything", inventory)[0] is None
    finally:
        engine.close()
