"""Verified endpoints and pour-aware targets, against a real engine.

Two policies are pinned here:

* an endpoint the point-identity rule cannot name (a track-only cluster with no
  pad) is re-anchored on copper the engine *proves* carries the scheduled net -
  never guessed;
* a pour-aware waypoint is only offered when the engine proves it lies in the
  **far terminal's own** connected component, which is what makes closing
  ``pad -> waypoint`` close the connection. Geometry alone proves nothing: a hole,
  a keepout or an isolated same-net island simply has no shared cluster.

All boards here are generated by the repository's synthetic fixture helper.
"""

from __future__ import annotations

from pcb_world.agent.observations import (
    CopperAnchorIndex,
    LayerResolver,
    anchor_diagnosis,
    component_anchor_candidates,
    component_waypoints,
    reanchor_pair,
    verified_anchor,
    zone_anchor,
)
from pcb_world.agent.observations import NetPair
from tests.agent import synthetic_boards as sb


def _pair(net: int, start, target, *, gap: float = 20.0) -> NetPair:
    return NetPair(
        net_code=net, net_name=sb.net_name(net), start=start, target=target,
        gap_mm=gap, start_layers=(start[2],), target_layers=(target[2],),
        pad_groups=2,
    )


def test_a_track_only_cluster_is_proved_by_its_own_copper(native_engine_checked, board_dir):
    """The net comes from the cluster's own items, not from a pad that is absent."""
    from pcb_world.engine import KiCadEngine

    board = sb.write_board(
        board_dir / "track_only.kicad_pcb",
        pads=[sb.Pad("PA1", 40.0, 20.0, 1)],
        segments=[sb.Segment(10.0, 10.0, 20.0, 10.0, 1)],
        nets=(1,), width=50.0, height=30.0,
    )
    engine = KiCadEngine(board)
    try:
        assert engine.get_pads()
        from pcb_world.agent.session import AgentSession

        session = AgentSession(engine, board_path=board)
        assert session.net_at(15.0, 10.0, 1) == 0        # no pad in the cluster

        resolution = verified_anchor(session, 15.0, 10.0, 1, 1)
        assert resolution is not None, "a same-net track cluster must be provable"
        assert resolution.proof == "copper"
        assert resolution.net_code == 1
        # A different net is never accepted for this cluster.
        assert verified_anchor(session, 15.0, 10.0, 1, 2) is None

        pair = _pair(1, (15.0, 10.0, 1), (40.0, 20.0, 1))
        reanchored = reanchor_pair(session, pair)
        assert reanchored is not None
        updated, evidence = reanchored
        assert evidence["endpoints"]["start"]["replaced"]["proof"] == "copper"
        # The replacement is a real anchor of that same track, at the same net.
        assert updated.start[2] == 1
        assert updated.target == pair.target
        assert evidence["endpoints"]["target"]["kept"] is True
    finally:
        engine.close()


def test_pour_waypoints_only_ever_land_in_the_far_terminal_component(
    native_engine_checked, board_dir
):
    """A same-net island that is *not* connected to the target is never offered."""
    from pcb_world.engine import KiCadEngine
    from pcb_world.agent.session import AgentSession

    # PA1 sits alone; PB1 sits inside a pour (its own component); a second pour of
    # the same net is an isolated island in the far corner.
    board = sb.write_board(
        board_dir / "pour_components.kicad_pcb",
        pads=[sb.Pad("PA1", 5.0, 5.0, 1), sb.Pad("PB1", 30.0, 10.0, 1)],
        nets=(1,), width=40.0, height=24.0,
        zones=[
            sb.Zone(1, 20.0, 5.0, 38.0, 20.0, fill_points=(
                (20.0, 5.0), (38.0, 5.0), (38.0, 20.0), (20.0, 20.0))),
            sb.Zone(1, 1.0, 18.0, 8.0, 23.0, fill_points=(
                (1.0, 18.0), (8.0, 18.0), (8.0, 23.0), (1.0, 23.0))),
        ],
    )
    engine = KiCadEngine(board)
    try:
        session = AgentSession(engine, board_path=board)
        engine.build_connectivity()
        pair = _pair(1, (5.0, 5.0, 1), (30.0, 10.0, 1))
        target_anchors = session.cluster(*pair.target)
        assert target_anchors, "the target pad must sit on copper"

        points = component_waypoints(session, pair, limit=3, samples=16)
        assert points, "the pour must offer an escape point"

        for point in points:
            cluster = session.cluster(point["x_mm"], point["y_mm"], point["layer"])
            assert cluster & target_anchors, point
            assert point["shared_anchors"] >= 1
            # The isolated island is never a candidate: it shares no copper with
            # the far terminal, so routing to it could not close the connection.
            assert not (point["x_mm"] < 10.0 and point["y_mm"] > 17.0), point
    finally:
        engine.close()


def test_pour_samples_never_land_in_a_hole_or_on_another_layer(
    native_engine_checked, board_dir
):
    """The proof is connectivity, so a hole and a wrong layer are both excluded."""
    from pcb_world.engine import KiCadEngine
    from pcb_world.agent.session import AgentSession

    # An L-shaped pour: its bounding-box centre has no copper (the hole), and the
    # pour exists on F.Cu only.
    board = sb.write_board(
        board_dir / "pour_hole.kicad_pcb",
        pads=[sb.Pad("PA1", 2.0, 2.0, 1), sb.Pad("PB1", 10.0, 10.0, 1)],
        nets=(1,), width=40.0, height=24.0, copper_layers=4,
        zones=[sb.Zone(1, 5.0, 5.0, 25.0, 20.0, layer="F.Cu", fill_points=(
            (5.0, 5.0), (25.0, 5.0), (25.0, 10.0), (10.0, 10.0), (10.0, 20.0),
            (5.0, 20.0)))],
    )
    engine = KiCadEngine(board)
    try:
        session = AgentSession(engine, board_path=board)
        engine.build_connectivity()
        pair = _pair(1, (2.0, 2.0, 1), (10.0, 10.0, 1))
        target_anchors = session.cluster(*pair.target)
        assert target_anchors
        assert not session.cluster(18.0, 15.0, 1), "the hole must carry no copper"

        points = component_waypoints(session, pair, limit=4, samples=25)
        assert points
        for point in points:
            assert point["layer"] == 1
            cluster = session.cluster(point["x_mm"], point["y_mm"], point["layer"])
            assert cluster & target_anchors
            # Never the empty middle of the L, and never on the back copper.
            assert not (15.0 < point["x_mm"] < 22.0
                        and 12.0 < point["y_mm"] < 18.0), point
    finally:
        engine.close()


def test_an_anchor_on_no_copper_is_named_precisely_and_never_guessed(
    native_engine_checked, board_dir
):
    """An empty anchor is reported as geometry, not retried as a routing failure."""
    from pcb_world.engine import KiCadEngine
    from pcb_world.agent.session import AgentSession

    board = sb.write_board(
        board_dir / "empty_anchor.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PB1", 40.0, 10.0, 1)],
        segments=[sb.Segment(24.0, 14.0, 26.0, 14.0, 2)],     # foreign copper nearby
        nets=(1, 2), width=50.0, height=30.0,
    )
    engine = KiCadEngine(board)
    try:
        session = AgentSession(engine, board_path=board)
        engine.build_connectivity()
        # A point 1 mm above a net-2 track: real copper is close, but none of it
        # belongs to net 1, and the point itself carries no copper at all.
        diagnosis = anchor_diagnosis(session, (25.0, 15.0, 1), 1)
        assert diagnosis["layers"] == {}
        assert "carries no copper on any copper layer" in diagnosis["verdict"]
        assert diagnosis["nearest_foreign"] is not None
        assert diagnosis["nearest_foreign"]["distance_mm"] <= 1.05
        assert diagnosis["nearest_same_net"] is None

        pair = _pair(1, (25.0, 15.0, 1), (40.0, 10.0, 1))
        assert reanchor_pair(session, pair) is None      # never guessed
    finally:
        engine.close()


def test_a_bare_anchor_is_offered_the_nets_own_copper_as_a_labelled_candidate(
    native_engine_checked, board_dir
):
    """An empty anchor does not retire the connection: the net's copper is offered.

    A ratsnest point can land on no copper of the scheduled net while the net's
    terminals are a millimetre away. Refusing the pair there would report a
    routable connection as unroutable, so the nearest proved anchor of the same
    net becomes a *candidate* endpoint - labelled as such, never presented as the
    anchor the ratsnest offered.
    """
    from pcb_world.engine import KiCadEngine
    from pcb_world.agent.session import AgentSession

    board = sb.write_board(
        board_dir / "component_candidate.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PB1", 40.0, 10.0, 1)],
        segments=[sb.Segment(24.0, 14.0, 26.0, 14.0, 2)],     # foreign copper nearby
        nets=(1, 2), width=50.0, height=30.0,
    )
    engine = KiCadEngine(board)
    try:
        session = AgentSession(engine, board_path=board)
        engine.build_connectivity()
        # No copper of net 1 within 4 mm: nothing may be offered.
        assert component_anchor_candidates(session, (25.0, 15.0, 1), 1) == []
        # PA1 is 1 mm from this point, so the net's own copper is in reach.
        candidates = component_anchor_candidates(session, (10.0, 11.0, 1), 1)
        assert candidates, "the net's own copper must be offered"
        nearest = candidates[0]
        assert nearest.net_code == 1
        assert nearest.provenance == "candidate"
        assert nearest.proof == "pad"
        assert nearest.moved_mm <= 1.05
        # The foreign net is never offered for net 1, and net 1 is never offered
        # for net 2's copper.
        assert all(candidate.net_code == 1 for candidate in candidates)
        assert component_anchor_candidates(session, (25.0, 14.0, 1), 1) == []

        pair = _pair(1, (10.0, 11.0, 1), (40.0, 10.0, 1))
        reanchored = reanchor_pair(session, pair)
        assert reanchored is not None
        updated, evidence = reanchored
        replaced = evidence["endpoints"]["start"]["replaced"]
        assert replaced["provenance"] == "candidate"
        assert replaced["moved_mm"] > 0.0
        assert updated.start != pair.start
        assert evidence["component_candidates"]["start"]

        # The candidate search stays inside its radius: a point far from any of
        # the net's copper is still refused rather than guessed.
        assert component_anchor_candidates(
            session, (25.0, 25.0, 1), 1, radius_mm=2.0
        ) == []
    finally:
        engine.close()


class _CountingSession:
    """A pour sample whose cluster is proved by the engine, with no real engine.

    The synthetic board helper does not fill zones the way a saved board's
    ``filled_polygon`` does, so the *labelling* contract is pinned against a
    stub: what a pour sample proves is tested against the real engine by
    ``test_pour_waypoints_only_ever_land_in_the_far_terminal_component`` and by
    the V3 board itself, and what it is *called* is tested here.
    """

    class _Item:
        kind = "zone"

        def __init__(self, physical_id: str) -> None:
            self.physical_id = physical_id
            self.net_code = 1

    class _Engine:
        def __init__(self, session: "_CountingSession") -> None:
            self._session = session

        def get_board_items(self):
            return list(self._session._items)

    def __init__(self) -> None:
        # zone | uuid | board layer 0 | corner | bbox in nm | ...
        self._items = [self._Item(
            "zone|00000000-0000-4000-8000-000000000001|0|10000000,10000000"
            "|10000000,10000000,10000000,10000000|"
        )]
        self._cluster = frozenset({(16.0, 14.0, 1)})
        self._engine = self._Engine(self)

    def cluster(self, x_mm: float, y_mm: float, layer: int) -> frozenset:
        return self._cluster


class _StubResolver:
    """Board layer 0 is copper layer 1 on this fixture."""

    @staticmethod
    def human(board_layer: int) -> int:
        return int(board_layer) + 1


def test_a_pour_re_anchor_is_labelled_a_candidate_not_the_original_endpoint():
    """The samples prove *a* point on the pour; they never prove the ratsnest point."""
    session = _CountingSession()
    index = CopperAnchorIndex()
    # One net-1 anchor inside the sampled cluster: the net is proved by that item.
    index._by_key[(16.0, 14.0, 1)] = [("track", 1)]

    resolution = zone_anchor(
        session, (10.0, 10.0, 1), 1, index=index, resolver=_StubResolver(),
        samples=4,
    )
    assert resolution is not None
    assert resolution.proof == "pour"
    assert resolution.provenance == "candidate"
    assert resolution.moved_mm > 0.0
    # The evidence a report carries says the same thing.
    assert resolution.to_evidence()["provenance"] == "candidate"
    assert resolution.to_evidence()["moved_mm"] > 0.0
