"""The read-only point-in-zone query and the advisory prefilter built on it.

Two things are pinned here, and they are different claims:

* the **engine query** answers what zone geometry covers a point — every
  covering zone, its net, its fill geometry, its layer span, its keepout flags,
  and an honest (never optimistic) statement about the provenance of the fill it
  read;
* the **prefilter** turns that into a ranking signal, and its contract is that
  unknown passes through untouched, no candidate is ever dropped, and the
  transactional DRC stays the only authority. (Its engine-free policy —
  unknown/disabled handling, the margin, the ordering rule — is pinned in
  ``test_zone_prefilter_unit.py``; this file covers it against real zone
  geometry.)

All boards are generated by the repository's synthetic fixture helper.
"""

from __future__ import annotations

import math
from pathlib import Path
from types import SimpleNamespace

import pytest

from pcb_world.agent import zone_coverage as zc
from pcb_world.agent.runner import RoutingRunner
from pcb_world.agent.session import AgentSession
from tests.agent import synthetic_boards as sb
from pcb_world.agent.observations import edge_key
from tests.agent.test_zone_prefilter_unit import (
    _NoQueryEngine,
    _RankingStub,
    _candidate,
)


def _session(engine, board: str) -> AgentSession:
    return AgentSession(engine, board_path=board)


def _pair(net: int, start, target) -> "object":
    from pcb_world.agent.observations import NetPair

    return NetPair(
        net_code=net, net_name=sb.net_name(net), start=start, target=target,
        gap_mm=10.0, start_layers=(start[2],), target_layers=(target[2],),
        pad_groups=2,
    )


# ---------------------------------------------------------------------------
# The engine query, against a real engine
# ---------------------------------------------------------------------------

def test_overlapping_zones_are_all_reported_never_one_hidden_net(
    engine_factory, board_dir,
):
    """A point in two pours must name both; naming one would hide the other."""
    board = sb.write_board(
        board_dir / "overlap.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PA2", 12.0, 12.0, 2)],
        zones=[
            sb.Zone(net=1, x0=0.0, y0=0.0, x1=20.0, y1=20.0,
                    fill_points=((0.0, 0.0), (20.0, 0.0), (20.0, 20.0), (0.0, 20.0))),
            sb.Zone(net=2, x0=5.0, y0=5.0, x1=15.0, y1=15.0,
                    fill_points=((5.0, 5.0), (15.0, 5.0), (15.0, 15.0), (5.0, 15.0))),
        ],
        nets=(1, 2), width=25.0, height=25.0,
    )
    engine = engine_factory(board)
    top = engine.layer_map.board_layer_order[0]

    rows = engine.get_zone_point_hits(((10.0, 10.0, top), (18.0, 18.0, top), (23.0, 23.0, top)))

    assert [row.query_index for row in rows] == [0, 1, 2]

    both = rows[0]
    assert both.status == "resolved"
    assert both.classification == "fill_multi_net"
    assert both.fill_net_code == -1, "a conflict must not be resolved to one net"
    assert sorted(hit.net_code for hit in both.hits) == [1, 2]
    assert all(hit.in_fill and hit.distance_mm == 0.0 for hit in both.hits)

    single = rows[1]
    assert single.classification == "fill_single_net"
    assert single.fill_net_code == 1
    assert [hit.net_code for hit in single.hits] == [1]

    outside = rows[2]
    assert outside.status == "resolved"
    assert outside.classification == "no_zone"
    assert list(outside.hits) == []


def test_a_void_inside_a_pour_is_outline_only_with_real_distance(
    engine_factory, board_dir,
):
    """The gap a foreign pour leaves around existing copper is the whole point."""
    board = sb.write_board(
        board_dir / "void.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1)],
        zones=[sb.Zone(
            net=1, x0=0.0, y0=0.0, x1=20.0, y1=20.0,
            fill_points=((5.0, 5.0), (15.0, 5.0), (15.0, 15.0), (5.0, 15.0)))],
        nets=(1,), width=25.0, height=25.0,
    )
    engine = engine_factory(board)
    top = engine.layer_map.board_layer_order[0]

    filled, in_void, outside = engine.get_zone_point_hits(
        ((10.0, 10.0, top), (10.0, 2.0, top), (23.0, 23.0, top)))

    assert filled.classification == "fill_single_net"
    assert filled.hits[0].in_fill is True
    assert filled.hits[0].distance_mm == pytest.approx(0.0)

    # Inside the zone outline, outside its copper: a void, measured.
    assert in_void.classification == "outline_only"
    assert in_void.hits[0].in_outline is True
    assert in_void.hits[0].in_fill is False
    # 3 mm straight below the fill's y=5 edge, so the distance is axial and exact.
    assert in_void.hits[0].distance_mm == pytest.approx(3.0, abs=1e-6)
    assert in_void.fill_provenance == "loaded_unverified"

    assert outside.classification == "no_zone"


def test_a_zone_spanning_copper_layers_is_tested_on_every_layer(
    engine_factory, board_dir,
):
    layered = sb.write_board(
        board_dir / "span.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PA2", 12.0, 12.0, 2)],
        zones=[
            sb.Zone(net=1, x0=0.0, y0=0.0, x1=20.0, y1=20.0, layer="F.Cu",
                    extra_layers=("In1.Cu", "B.Cu"),
                    fill_points=((0.0, 0.0), (20.0, 0.0), (20.0, 20.0), (0.0, 20.0))),
            sb.Zone(net=2, x0=2.0, y0=2.0, x1=18.0, y1=18.0, layer="F.Cu",
                    fill_points=((2.0, 2.0), (18.0, 2.0), (18.0, 18.0), (2.0, 18.0))),
        ],
        nets=(1, 2), width=25.0, height=25.0, copper_layers=4,
    )
    engine = engine_factory(layered)
    assert engine.layer_map.board_layer_order == [0, 4, 6, 2]
    front, inner1, inner2, back = engine.layer_map.board_layer_order

    rows = engine.get_zone_point_hits(
        ((10.0, 10.0, front), (10.0, 10.0, inner1), (10.0, 10.0, inner2),
         (10.0, 10.0, back)))

    # The spanning pour is on three of the four layers; the single-layer one is
    # only on the front, and the untouched layer answers no_zone.
    assert sorted(hit.net_code for hit in rows[0].hits) == [1, 2]
    assert [hit.net_code for hit in rows[1].hits] == [1]
    assert rows[1].hits[0].layer == inner1
    assert list(rows[2].hits) == []
    assert [hit.net_code for hit in rows[3].hits] == [1]
    assert rows[3].hits[0].layer == back


def test_rule_area_keepouts_report_flags_and_stay_out_of_the_copper_question(
    engine_factory, board_dir,
):
    board = sb.write_board(
        board_dir / "keepout.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1)],
        zones=[sb.Zone(net=0, x0=0.0, y0=0.0, x1=20.0, y1=20.0,
                       keepout=("tracks", "vias"))],
        nets=(1,), width=25.0, height=25.0,
    )
    engine = engine_factory(board)
    top = engine.layer_map.board_layer_order[0]

    row = engine.get_zone_point_hits(((10.0, 10.0, top),))[0]

    assert row.status == "resolved"
    assert row.in_keepout is True
    assert row.keepout_flags == 3          # tracks + vias
    assert [hit.is_rule_area for hit in row.hits] == [True]
    assert row.hits[0].in_fill is False
    # A keepout is not pour copper: it does not become a net-identity conflict.
    assert row.classification == "outline_only"
    assert row.fill_net_code == -1


def test_island_flag_is_reported_for_the_covering_fill_polygon(
    engine_factory, board_dir,
):
    island_board = sb.write_board(
        board_dir / "island.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1)],
        zones=[sb.Zone(net=1, x0=0.0, y0=0.0, x1=20.0, y1=20.0, island=True,
                       fill_points=((0.0, 0.0), (20.0, 0.0), (20.0, 20.0), (0.0, 20.0)))],
        nets=(1,), width=25.0, height=25.0,
    )
    solid_board = sb.write_board(
        board_dir / "not_island.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1)],
        zones=[sb.Zone(net=1, x0=0.0, y0=0.0, x1=20.0, y1=20.0, island=False,
                       fill_points=((0.0, 0.0), (20.0, 0.0), (20.0, 20.0), (0.0, 20.0)))],
        nets=(1,), width=25.0, height=25.0,
    )

    island = engine_factory(island_board)
    solid = engine_factory(solid_board)
    layer = island.layer_map.board_layer_order[0]

    assert island.get_zone_point_hits(((10.0, 10.0, layer),))[0].hits[0].fill_is_island is True
    assert solid.get_zone_point_hits(((10.0, 10.0, layer),))[0].hits[0].fill_is_island is False


def test_a_board_with_no_zones_answers_no_zone_rather_than_failing(
    engine_factory, board_dir,
):
    board = sb.write_board(
        board_dir / "no_zones.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PA2", 20.0, 10.0, 1)],
        nets=(1,), width=25.0, height=25.0,
    )
    engine = engine_factory(board)
    layer = engine.layer_map.board_layer_order[0]

    row = engine.get_zone_point_hits(((10.0, 10.0, layer),))[0]

    assert row.status == "resolved"
    assert row.classification == "no_zone"
    assert row.zones_tested == 0
    assert row.fill_provenance == "no_fill"
    assert list(row.hits) == []


def test_a_non_copper_layer_is_unknown_not_empty(engine_factory, board_dir):
    """`unknown` and `no_zone` must never be the same answer."""
    board = sb.write_board(
        board_dir / "layer_check.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1)],
        nets=(1,), width=25.0, height=25.0,
    )
    engine = engine_factory(board)
    # This enum orders the stack F_Cu=0, B_Cu=2, In1_Cu=4 (+2 per inner layer),
    # so "the last copper id plus ten" can still be a copper layer. A negative
    # id is unambiguously not one.
    non_copper = -1

    row = engine.get_zone_point_hits(((10.0, 10.0, non_copper),))[0]

    assert row.status == "unknown"
    assert row.reason
    assert row.classification == "unknown"


# ---------------------------------------------------------------------------
# The prefilter, over a real engine
# ---------------------------------------------------------------------------

def test_an_unfilled_pour_is_unknown_for_the_prefilter(engine_factory, board_dir):
    """'No stored fill' is not proof that the current rules put no copper there."""
    board = sb.write_board(
        board_dir / "unfilled.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PA2", 12.0, 12.0, 2)],
        zones=[sb.Zone(net=1, x0=0.0, y0=0.0, x1=20.0, y1=20.0)],   # no filled_polygon
        nets=(1, 2), width=25.0, height=25.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)

    verdict = coverage.verdict((10.0, 10.0, 1), 2, margin_mm=0.5)

    assert verdict.state == zc.UNKNOWN
    assert "no stored fill" in verdict.reason

    risk = coverage.candidate_risk([(10.0, 10.0, 1)], 2, margin_mm=0.5)
    assert risk.state == zc.UNKNOWN
    assert risk.suppressed is False


def test_own_foreign_and_mixed_are_distinguished_by_net_and_margin(
    engine_factory, board_dir,
):
    board = sb.write_board(
        board_dir / "nets.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PA2", 12.0, 12.0, 2)],
        zones=[
            sb.Zone(net=1, x0=0.0, y0=0.0, x1=20.0, y1=20.0, layer="F.Cu",
                    fill_points=((0.0, 0.0), (20.0, 0.0), (20.0, 20.0), (0.0, 20.0))),
            sb.Zone(net=2, x0=30.0, y0=0.0, x1=40.0, y1=20.0, layer="F.Cu",
                    fill_points=((30.0, 0.0), (40.0, 0.0), (40.0, 20.0), (30.0, 20.0))),
        ],
        nets=(1, 2), width=45.0, height=25.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)

    # On net 1's pour: this is the candidate's own copper.
    assert coverage.verdict((10.0, 10.0, 1), 1, margin_mm=0.5).state == zc.OWN
    # On net 2's pour, planned for net 1: foreign.
    foreign = coverage.verdict((35.0, 10.0, 1), 1, margin_mm=0.5)
    assert foreign.state == zc.FOREIGN
    assert foreign.nets == (2,)
    # Empty space: no pour contact at all.
    assert coverage.verdict((25.0, 10.0, 1), 1, margin_mm=0.5).state == zc.NONE
    # A netless pour is nobody's own copper, so it counts as foreign.
    assert coverage.verdict((35.0, 10.0, 1), 0, margin_mm=0.5).state == zc.FOREIGN

    # The margin is what makes this a geometry test rather than a point test: a
    # 0 mm margin at a spot 0.4 mm off the pour is `none`, and the same spot
    # with the board's own copper radius + clearance is contact.
    # 0.2 mm to the right of net 2's pour edge at x=30.
    near = (29.8, 10.0, 1)
    assert coverage.verdict(near, 1, margin_mm=0.0).state == zc.NONE
    assert coverage.verdict(near, 1, margin_mm=0.5).state == zc.FOREIGN


def test_cache_lifecycle_and_refill_invalidation(engine_factory, board_dir):
    board = sb.write_board(
        board_dir / "cache.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1)],
        zones=[sb.Zone(net=1, x0=0.0, y0=0.0, x1=20.0, y1=20.0,
                       fill_points=((0.0, 0.0), (20.0, 0.0), (20.0, 20.0), (0.0, 20.0)))],
        nets=(1,), width=25.0, height=25.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)

    coverage.verdict((10.0, 10.0, 1), 1, margin_mm=0.5)
    first = coverage.stats
    assert (first["queries"], first["batches"], first["cache_hits"]) == (1, 1, 0)

    # A repeated point costs no engine call — the run's per-pair loops re-ask.
    coverage.verdict((10.0, 10.0, 1), 1, margin_mm=0.5)
    second = coverage.stats
    assert second["queries"] == 1
    assert second["cache_hits"] == 1

    # ... but a *different* margin is a different question.
    coverage.verdict((10.0, 10.0, 1), 1, margin_mm=0.0)
    assert coverage.stats["queries"] == 2

    # A refill rewrites the fill polygons under the cache: the epoch moves and
    # the answer is re-fetched rather than served from before the refill.
    assert engine.zone_fill_epoch == 0
    assert engine.fill_zones("") is True
    assert engine.zone_fill_epoch == 1
    after_refill = coverage.stats["queries"]
    coverage.verdict((10.0, 10.0, 1), 1, margin_mm=0.5)
    assert coverage.stats["queries"] == after_refill + 1

    coverage.invalidate()
    assert coverage.stats["cached_points"] == 0


def test_one_point_is_own_for_one_net_and_foreign_for_another(engine_factory, board_dir):
    """The cache holds *copper*, not a verdict: the net decides own vs foreign.

    Regression for a real defect: the row cache used to hold the classified
    verdict keyed by (point, margin) only, so the second pair to ask about the
    same copper — a different net — was handed the first pair's own/foreign
    answer and mis-ranked.
    """
    board = sb.write_board(
        board_dir / "cross_net.kicad_pcb",
        pads=[sb.Pad("PA1", 10.0, 10.0, 1), sb.Pad("PA2", 12.0, 12.0, 2)],
        zones=[sb.Zone(net=2, x0=0.0, y0=0.0, x1=20.0, y1=20.0, layer="F.Cu",
                       fill_points=((0.0, 0.0), (20.0, 0.0), (20.0, 20.0), (0.0, 20.0)))],
        nets=(1, 2), width=25.0, height=25.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)
    point = (10.0, 10.0, 1)

    # Cold: one engine row, classified for net 1 (the pour is net 2).
    cold_foreign = coverage.verdict(point, 1, margin_mm=0.5)
    assert cold_foreign.state == zc.FOREIGN
    assert cold_foreign.nets == (2,)
    cold_stats = coverage.stats

    # Warm, opposite net: the row is a cache hit, and the verdict must still flip.
    warm_own = coverage.verdict(point, 2, margin_mm=0.5)
    assert warm_own.state == zc.OWN
    assert warm_own.nets == (2,)
    after = coverage.stats
    assert after["queries"] == cold_stats["queries"], "the row came from the cache"
    assert after["cache_hits"] == cold_stats["cache_hits"] + 1

    # ... and back again: alternating pairs cannot poison each other.
    assert coverage.verdict(point, 1, margin_mm=0.5).state == zc.FOREIGN
    assert coverage.verdict(point, 2, margin_mm=0.5).state == zc.OWN
    assert coverage.stats["queries"] == cold_stats["queries"]

    # The same holds through the candidate-level aggregation the runner uses.
    corridor = [((0.0, 0.0, 1), (20.0, 0.0, 1))]
    assert coverage.candidate_risk(
        [], 1, margin_mm=0.5, legs=corridor, pitch_mm=1.0, max_samples=48).state == zc.FOREIGN
    assert coverage.candidate_risk(
        [], 2, margin_mm=0.5, legs=corridor, pitch_mm=1.0, max_samples=48).state == zc.OWN


def test_a_ranked_late_candidate_can_still_miss_the_truncated_sweep(
    engine_factory, board_dir,
):
    """Ranking keeps every candidate in the list; the sweep window still cuts.

    The prefilter never removes a candidate from the generated list, but the
    runner truncates to ``candidate_limit`` *after* ranking — so a plan ranked
    late can genuinely miss this attempt. That distinction is what makes "it
    never drops a plan" false, and this test pins the real behaviour.
    """
    board = sb.write_board(
        board_dir / "truncate.kicad_pcb",
        pads=[sb.Pad("PA1", 0.0, 10.0, 1), sb.Pad("PA2", 20.0, 10.0, 1),
              sb.Pad("PB1", 30.0, 10.0, 2)],
        zones=[sb.Zone(net=2, x0=25.0, y0=0.0, x1=45.0, y1=20.0, layer="F.Cu",
                       fill_points=((25.0, 0.0), (45.0, 0.0), (45.0, 20.0), (25.0, 20.0)))],
        nets=(1, 2), width=50.0, height=25.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    stub = _RankingStub(zc.ZoneCoverage(session), margin=(0.5, "test"))
    pair = _pair(1, (0.0, 10.0, 1), (20.0, 10.0, 1))
    candidates = [_candidate("through_pour", 35.0), _candidate("clear_a", 10.0),
                  _candidate("clear_b", 15.0)]

    ranked = RoutingRunner._zone_ranked(stub, session, pair, candidates, stub.config)
    assert [c.name for c in ranked] == ["clear_a", "clear_b", "through_pour"]

    swept = ranked[:2]                      # candidate_limit = 2
    assert [c.name for c in swept] == ["clear_a", "clear_b"]
    assert "through_pour" not in {c.name for c in swept}


# ---------------------------------------------------------------------------
# The runner's ranking hook
# ---------------------------------------------------------------------------


def test_a_real_engine_ranks_a_foreign_pour_plan_last(engine_factory, board_dir):
    """The integration the prefilter exists for, on real zone geometry."""
    board = sb.write_board(
        board_dir / "rank.kicad_pcb",
        pads=[sb.Pad("PA1", 0.0, 10.0, 1), sb.Pad("PA2", 20.0, 10.0, 1),
              sb.Pad("PB1", 40.0, 10.0, 2)],
        zones=[sb.Zone(net=2, x0=25.0, y0=0.0, x1=45.0, y1=20.0, layer="F.Cu",
                       fill_points=((25.0, 0.0), (45.0, 0.0), (45.0, 20.0), (25.0, 20.0)))],
        nets=(1, 2), width=50.0, height=25.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)
    stub = _RankingStub(coverage, margin=(0.5, "test"))
    # Net 1's pair; one plan's waypoint sits in net 2's pour, the other does not.
    candidates = [_candidate("through_pour", 35.0), _candidate("clear", 20.0)]
    pair = _pair(1, (0.0, 10.0, 1), (20.0, 10.0, 1))

    ranked = RoutingRunner._zone_ranked(stub, session, pair, candidates, stub.config)

    assert [candidate.name for candidate in ranked] == ["clear", "through_pour"]
    evidence = stub.state.metrics["zone_prefilter"]
    assert evidence["available"] is True
    assert evidence["candidates_ranked_late"] == 1
    # 41 corridor samples along the pair's 20 mm leg at the configured 0.5 mm
    # pitch, plus the one waypoint that is not already on that line. The second
    # candidate reuses every corridor point from the cache instead of re-asking.
    assert evidence["stats"]["queries"] == 42
    assert evidence["stats"]["cache_hits"] >= 41
    audit = evidence["pairs"][next(iter(evidence["pairs"]))]
    assert audit[0]["candidate"] == "through_pour"
    assert audit[0]["state"] == zc.FOREIGN


# ---------------------------------------------------------------------------
# The measured via-opening family
# ---------------------------------------------------------------------------

def test_openings_are_measured_clear_of_foreign_pour_and_land_on_the_far_layer(
    engine_factory, board_dir,
):
    """A cross-layer pair gets openings with real clearance, on the far layer."""
    board = sb.write_board(
        board_dir / "openings.kicad_pcb",
        pads=[sb.Pad("PA1", 2.0, 10.0, 1, kind="smd_top"),
              sb.Pad("PA2", 30.0, 10.0, 1, kind="smd_bottom")],
        # Net 2's pour covers the left half of the *far* layer: the via must
        # land clear of it, while the approach on the start layer is clear.
        zones=[sb.Zone(net=2, x0=0.0, y0=0.0, x1=14.0, y1=20.0, layer="B.Cu",
                       fill_points=((0.0, 0.0), (14.0, 0.0), (14.0, 20.0), (0.0, 20.0)))],
        nets=(1, 2), width=34.0, height=22.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)
    margin = 0.4

    openings = zc.find_openings(
        coverage, (2.0, 10.0, 1), (30.0, 10.0, 2), 1,
        margin_mm=margin, search_mm=3.0, pitch_mm=1.0, max_samples=64,
        max_openings=4, band_mm=1.0)

    assert openings, "the clear half of the corridor must offer openings"
    for opening in openings:
        x_mm, _y_mm, layer = opening.point
        assert layer == 2, "the transition layer is the far endpoint's layer"
        assert x_mm > 14.0 + margin, "no opening may sit inside net 2's pour"
        assert opening.clearance_mm >= margin
        assert opening.unknown is False
    # They are distinct places, not four names for one spot.
    xs = sorted(opening.point[0] for opening in openings)
    assert all(b - a >= 1.0 for a, b in zip(xs, xs[1:]))


def test_openings_on_a_same_layer_pair_and_without_an_engine_are_empty(
    engine_factory, board_dir,
):
    board = sb.write_board(
        board_dir / "same_layer.kicad_pcb",
        pads=[sb.Pad("PA1", 2.0, 10.0, 1), sb.Pad("PA2", 30.0, 10.0, 1)],
        nets=(1,), width=34.0, height=22.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)

    assert zc.find_openings(
        coverage, (2.0, 10.0, 1), (30.0, 10.0, 1), 1,
        margin_mm=0.4, search_mm=3.0, pitch_mm=1.0, max_samples=64,
        max_openings=4, band_mm=1.0) == []

    # No engine support: silent, not a guess.
    assert zc.find_openings(
        zc.ZoneCoverage(SimpleNamespace(_engine=_NoQueryEngine())),
        (2.0, 10.0, 1), (30.0, 10.0, 2), 1,
        margin_mm=0.4, search_mm=3.0, pitch_mm=1.0, max_samples=64,
        max_openings=4, band_mm=1.0) == []


def test_a_measured_opening_places_the_via_where_it_was_measured(
    engine_factory, board_dir,
):
    """The family's whole claim: the via lands at the measured point.

    A layer-changing waypoint is what controls this - the session emits
    ``make_via`` at the waypoint's own coordinate, and the arrival tolerance is
    the via's radius. This pins the end-to-end behaviour the family is built on,
    including that the opening is clear of the foreign pour that covers the other
    half of the corridor.
    """
    board = sb.write_board(
        board_dir / "via_at_opening.kicad_pcb",
        pads=[sb.Pad("PA1", 2.0, 10.0, 1, kind="smd_top"),
              sb.Pad("PA2", 30.0, 10.0, 1, kind="smd_bottom")],
        zones=[sb.Zone(net=2, x0=0.0, y0=0.0, x1=14.0, y1=20.0, layer="B.Cu",
                       fill_points=((0.0, 0.0), (14.0, 0.0), (14.0, 20.0), (0.0, 20.0)))],
        nets=(1, 2), width=34.0, height=22.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)
    openings = zc.find_openings(
        coverage, (2.0, 10.0, 1), (30.0, 10.0, 2), 1,
        margin_mm=0.4, search_mm=3.0, pitch_mm=1.0, max_samples=64,
        max_openings=3, band_mm=1.0)
    assert openings

    via_radius = float(engine.route_item_radius_mm(for_via=True))
    for opening in openings:
        x_mm, y_mm, layer = opening.point
        before = engine.get_via_count()
        snap = session.snapshot()
        result = session.connect_targets(
            (2.0, 10.0, 1), (30.0, 10.0, 2), "walkaround",
            waypoints=[(x_mm, y_mm, layer)], token=snap.token)
        if not result.accepted:
            # A refused attempt is a legitimate outcome (the DRC is the
            # authority); what must never happen is copper kept that DRC refused.
            assert not result.committed
            continue
        assert engine.get_via_count() > before
        vias = [v for v in engine.get_vias()
                if math.hypot(v.x_mm - x_mm, v.y_mm - y_mm) <= via_radius + 1e-6]
        assert vias, "the via must land at the measured opening"
        break
    else:  # pragma: no cover - only if every opening is refused
        pytest.fail("no measured opening produced a kept via")


def test_screening_reports_per_edge_status_without_touching_the_board(
    engine_factory, board_dir,
):
    """The cheap pass: measure every edge, mutate nothing, bound everything."""
    board = sb.write_board(
        board_dir / "screen.kicad_pcb",
        pads=[sb.Pad("PA1", 2.0, 10.0, 1, kind="smd_top"),
              sb.Pad("PA2", 30.0, 10.0, 1, kind="smd_bottom"),
              sb.Pad("PB1", 5.0, 6.0, 2), sb.Pad("PB2", 25.0, 6.0, 2)],
        zones=[sb.Zone(net=2, x0=0.0, y0=0.0, x1=14.0, y1=20.0, layer="B.Cu",
                       fill_points=((0.0, 0.0), (14.0, 0.0), (14.0, 20.0), (0.0, 20.0)))],
        nets=(1, 2), width=34.0, height=22.0,
    )
    engine = engine_factory(board)
    session = _session(engine, board)
    coverage = zc.ZoneCoverage(session)

    cross = ((2.0, 10.0, 1), (30.0, 10.0, 2))          # needs a via hop
    same = ((5.0, 6.0, 1), (25.0, 6.0, 1))             # already on one layer
    edges = [
        (edge_key(*cross), 1),
        (edge_key(*same), 2),
        (edge_key(*cross), 1),                          # budget: max_edges = 2
    ]
    vias_before, tracks_before = engine.get_via_count(), engine.get_track_count()

    rows = zc.screen_openings(coverage, edges, margin_mm=0.4, max_edges=2,
                              pitch_mm=1.0, max_samples=64, max_openings=2, band_mm=1.0)

    statuses = [row.status for row in rows]
    assert statuses[0] == "openings", statuses
    assert statuses[1] == "same_layer"
    assert statuses[2] == "budget"
    assert rows[0].openings and rows[0].openings[0].point[2] == 2
    assert rows[0].reason == ""
    assert "max_edges" in rows[2].reason

    summary = zc.screen_summary(rows)
    assert summary["total"] == 3
    assert summary["openings"] == 1 and summary["edges_with_openings"] == 1
    assert summary["same_layer"] == 1 and summary["budget"] == 1
    assert summary["openings_total"] == len(rows[0].openings)

    # Read-only: no copper, no route, no checkpoint.
    assert engine.get_via_count() == vias_before
    assert engine.get_track_count() == tracks_before
    assert not engine.is_routing()

    # A malformed key is unknown, never silently skipped.
    broken = zc.screen_openings(coverage, [((1.0, 2.0, 1), 1)], margin_mm=0.4)
    assert broken[0].status == "unknown" and "edge key" in broken[0].reason


def test_screening_without_the_query_is_unknown_not_empty(engine_factory, board_dir):
    coverage = zc.ZoneCoverage(SimpleNamespace(_engine=_NoQueryEngine()))
    rows = zc.screen_openings(
        coverage, [((0.0, 0.0, 1, 10.0, 0.0, 2), 1)], margin_mm=0.4)
    assert rows[0].status == "unknown"
    assert rows[0].reason


def test_the_screen_tool_records_board_provenance(
    native_engine_checked, board_dir, tmp_path,
):
    """A screen is evidence about one generation, so it must name that generation."""
    import hashlib
    import json as _json

    from tools.reliability import screen_zone_openings as tool

    board = sb.write_board(
        board_dir / "provenance.kicad_pcb",
        pads=[sb.Pad("PA1", 2.0, 10.0, 1, kind="smd_top"),
              sb.Pad("PA2", 30.0, 10.0, 1, kind="smd_bottom")],
        zones=[sb.Zone(net=2, x0=0.0, y0=0.0, x1=14.0, y1=20.0, layer="B.Cu",
                       fill_points=((0.0, 0.0), (14.0, 0.0), (14.0, 20.0), (0.0, 20.0)))],
        nets=(1, 2), width=34.0, height=22.0,
    )
    edges_path = tmp_path / "edges.json"
    edges_path.write_text(_json.dumps([
        {"edge": [2.0, 10.0, 1, 30.0, 10.0, 2], "net_code": 1}]))
    out = tmp_path / "screen.json"

    exit_code = tool.main([
        "--board", board, "--project", str(Path(board).with_suffix(".kicad_pro")),
        "--edges", str(edges_path), "--out", str(out)])

    assert exit_code == 0
    payload = _json.loads(out.read_text())
    expected = hashlib.sha256(Path(board).read_bytes()).hexdigest()
    assert payload["board_sha256"] == expected
    assert payload["project_sha256"]  # the sibling project is hashed too
    assert payload["rules_sha256"] is None       # no rule file beside this board
    assert payload["summary"]["total"] == 1
    # The helper is honest about a missing file rather than inventing a hash.
    assert tool.sha256_file(str(tmp_path / "absent.kicad_pcb")) is None


# ---------------------------------------------------------------------------
# The via's real layer span
# ---------------------------------------------------------------------------

def test_an_interior_layer_foreign_zone_disqualifies_a_four_layer_opening(
    engine_factory, board_dir,
):
    """A via's barrel and hole exist on interior layers too.

    Regression for a measured defect: the screen asked only about the two layers
    the plan changes between, so an opening could be reported clear while the via
    sat inside a foreign plane on an interior layer. On a four-layer board the
    foreign zone here lives on an *interior* layer and covers the whole corridor,
    so no opening may be offered even though both endpoint layers are clear.
    """
    def board_with(interior_zone):
        zones = []
        if interior_zone:
            zones.append(sb.Zone(net=2, x0=0.0, y0=0.0, x1=34.0, y1=22.0,
                                 layer="In1.Cu",
                                 fill_points=((0.0, 0.0), (34.0, 0.0),
                                              (34.0, 22.0), (0.0, 22.0))))
        return sb.write_board(
            board_dir / ("interior_zone.kicad_pcb" if interior_zone else "interior_clear.kicad_pcb"),
            pads=[sb.Pad("PA1", 2.0, 10.0, 1, kind="smd_top"),
                  sb.Pad("PA2", 30.0, 10.0, 1, kind="smd_bottom")],
            zones=zones, nets=(1, 2), width=34.0, height=22.0, copper_layers=4)

    blocked = engine_factory(board_with(True))
    clear = engine_factory(board_with(False))
    args = dict(margin_mm=0.4, search_mm=3.0, pitch_mm=1.0, max_samples=64,
                max_openings=3, band_mm=1.0)

    assert zc.via_layer_span(zc.ZoneCoverage(_session(blocked, board_with(True)))) == (1, 2, 3, 4)
    assert zc.find_openings(
        zc.ZoneCoverage(_session(blocked, board_with(True))),
        (2.0, 10.0, 1), (30.0, 10.0, 4), 1, **args) == []

    # The control differs only by that interior pour, and does offer openings.
    openings = zc.find_openings(
        zc.ZoneCoverage(_session(clear, board_with(False))),
        (2.0, 10.0, 1), (30.0, 10.0, 4), 1, **args)
    assert openings
    assert zc.via_layer_span(zc.ZoneCoverage(_session(clear, board_with(False)))) == (1, 2, 3, 4)


def test_the_screen_is_two_layer_compatible_and_its_queries_are_bounded(
    engine_factory, board_dir,
):
    board = sb.write_board(
        board_dir / "two_layer.kicad_pcb",
        pads=[sb.Pad("PA1", 2.0, 10.0, 1, kind="smd_top"),
              sb.Pad("PA2", 30.0, 10.0, 1, kind="smd_bottom")],
        zones=[sb.Zone(net=2, x0=0.0, y0=0.0, x1=14.0, y1=20.0, layer="B.Cu",
                       fill_points=((0.0, 0.0), (14.0, 0.0), (14.0, 20.0), (0.0, 20.0)))],
        nets=(1, 2), width=34.0, height=22.0)
    engine = engine_factory(board)
    coverage = zc.ZoneCoverage(_session(engine, board))

    # A two-layer stack is still both layers, in order.
    assert zc.via_layer_span(coverage) == (1, 2)
    vias_before, tracks_before = engine.get_via_count(), engine.get_track_count()

    max_samples = 33                   # 28 mm corridor at 1 mm pitch
    openings = zc.find_openings(
        coverage, (2.0, 10.0, 1), (30.0, 10.0, 2), 1,
        margin_mm=0.4, search_mm=3.0, pitch_mm=1.0, max_samples=max_samples,
        max_openings=3, band_mm=1.0)

    assert openings, "a two-layer board with a clear half-corridor still offers openings"
    # Bounded: at most one query per (corridor position, spanned layer), and
    # the layer-changing leg's own duplication is deduplicated before the query.
    assert coverage.stats["queries"] <= (max_samples + 1) * 2
    assert coverage.stats["cached_points"] == coverage.stats["queries"]
    # Read-only: finding openings never touches the board.
    assert engine.get_via_count() == vias_before
    assert engine.get_track_count() == tracks_before
    assert not engine.is_routing()


def test_a_board_with_no_zones_offers_openings_on_every_spanning_layer(
    engine_factory, board_dir,
):
    """Nothing to clear means nothing disqualifies — the span check must not fire."""
    board = sb.write_board(
        board_dir / "no_zones_span.kicad_pcb",
        pads=[sb.Pad("PA1", 2.0, 10.0, 1, kind="smd_top"),
              sb.Pad("PA2", 30.0, 10.0, 1, kind="smd_bottom")],
        nets=(1,), width=34.0, height=22.0, copper_layers=4)
    engine = engine_factory(board)
    coverage = zc.ZoneCoverage(_session(engine, board))

    openings = zc.find_openings(
        coverage, (2.0, 10.0, 1), (30.0, 10.0, 4), 1,
        margin_mm=0.4, search_mm=3.0, pitch_mm=5.0, max_samples=16,
        max_openings=2, band_mm=1.0)

    assert openings
    assert all(opening.unknown is False for opening in openings)
